setwd("G:/Columbia/STAT GR5243/project02")
library(RSelenium)
checkForServer()
startServer()
mybrowser<-remoteDriver()
mybrowser$open()
mybrowser$navigate("http://www1.nyc.gov/nyc-resources/service/2195/pay-a-parking-ticket")
wxbox<-mybrowser$findElement(using='css selector','.link-arrow-blue')
wxbox$clickElement()
wxbox01<-mybrowser$findElement(using='css selector','#args\\.PLATE')
wxbox01$sendKeysToElement(list("98255MB","\uE007"))
wxbox02<-mybrowser$findElement(using='css selector','#sm_total_add_all')
wxbox02$clickElement()
mybrowser$screenshot(display=TRUE)

